apiVersion: v1
kind: Pod
metadata:
  name: arm64-spot-pod
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    eks.amazonaws.com/capacityType: SPOT
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:latest
